version: '3.9'
services:
  frontend:
    container_name: app-front-at-group
    build: ./frontend
    ports:
      - 5173:5173
    working_dir: /app-frontend
    restart: 'always'
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:5173" ]
      timeout: 10s
      retries: 5
  backend:
    container_name: app-back-at-group
    user: node
    build: ./backend
    restart: 'always'
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
