version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306

  backend:
    container_name: app_backend
    build: ./backend
    restart: always
    volumes:
      - ./backend/src:/app-backend/src
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - APP_PORT=5000
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306

  frontend:
    container_name: app_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app-frontend/src
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
